version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7.2-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8220 public/index.php
        environment:
            docker: "true"
        ports:
            - 8220:8220
        volumes:
            - .:/var/www
            - logs:/var/www/logs
