version: 2
jobs:
    test:
        docker:
            - image: circleci/php:7.2.1-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "composer.json" }}
                - v1-dependencies-
            - run:
                name: Composer Install
                command: composer install -n --prefer-dist
            - save_cache:
                  paths:
                      - ./vendor
                  key: v1-dependencies-{{ checksum "composer.json" }}
            - run:
                name: Test
                command: composer test
    build:
        docker:
            - image: circleci/php:7.2.1-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "composer.json" }}
                - v1-dependencies-
            - run:
                name: Composer install
                command: composer install -n --prefer-dist --no-dev
            - save_cache:
                paths:
                    - ./vendor
                key: v1-dependencies-{{ checksum "composer.json" }}
            - run:
                name: Create artifacts file
                command: |
                    mkdir artifacts
                    tar --exclude='*.tgz' --exclude='./.git' --exclude='./artifacts' -zvcf artifacts/artifacts.tgz
            - run:
                name: Authorize with Google Cloud
                command: |
                    echo $GCLOUD_CI_AUTH_SECRET | base64 --decode > gcloud-auth-secret.json
                    gcloud auth activate-service-account --key-file gcloud-auth-secret.json
    deploy:
        docker:
            - image: circleci/php:7.2.1-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Deploy
                command: find .
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test
            - deploy:
                requires:
                    - build
                    - test
