version: 2
jobs:
    build:
        docker:
            - image: circleci/php:7.2-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "composer.json" }}
                - v1-dependencies-
            - run:
                name: Composer Install
                command: composer install -n --prefer-dist
            - save_cache:
                  paths:
                      - ./vendor
                  key: v1-dependencies-{{ checksum "composer.json" }}
            - run:
                name: Test
                command: composer test-all
deployment:
    staging:
        branch: master
        heroku:
            appname: work-calendar-api-staging
#workflows:
#    version: 2
#    standard:
#        jobs:
#            - build
#            - deploy-to-staging:
#                requires:
#                    - build
